### PR TITLE
Run the build script before running the tests

### LINKED ISSUE #42: None of the tests are passing
I cloned the repo to poke at an issue, installed, and ran the tests, and they all fail.

It appears that the tests always return an empty string right now.

Tested on `e1d8f5c` (the latest commit in the master branch as I write this issue).

Here's the output of the final test as an example:

```
# sample output indented: skip.js
not ok 28 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\nok 1 - hey hey\nok 2 - hey hey bis\n# Subtest: hello world\n    ok 1 - should be truthy\n    # Subtest: blah\n        1..0\n    ok 2 - blah # SKIP\n    # Subtest: for some reason\n        1..0\n    ok 3 - for some reason # SKIP\n    1..3\nok 3 - hello world # {TIME}\n# Subtest: failing text\n    1..0\nok 4 - failing text # SKIP\n1..4\n\n# ok\n# success: 3\n# skipped: 3\n# failure: 0\n'
    actual: |-
      ''
    at: Socket.cp.stdout.on (/Users/josh/code/zora/test/samples/index.js:37:15)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/josh/code/zora/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/Users/josh/code/zora/node_modules/tape/lib/test.js:77:32)
          at Test.equal (/Users/josh/code/zora/node_modules/tape/lib/test.js:386:10)
          at Test.bound [as equal] (/Users/josh/code/zora/node_modules/tape/lib/test.js:77:32)
          at Socket.cp.stdout.on (/Users/josh/code/zora/test/samples/index.js:37:15)
          at Socket.emit (events.js:194:15)
          at endReadableNT (_stream_readable.js:1125:12)
          at process._tickCallback (internal/process/next_tick.js:63:19)
  ...

1..28
# tests 28
# pass  0
# fail  28
```

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #42

### CODE REVIEW

**Comment by TehShrike** [comment]
😬 

Sooooo the test script won't actually test the codebase?  That doesn't seem right.

**Comment by lorenzofox3** [comment]
Technically yes. 
I see it more like ``test`` task depends on ``build source`` and eventually ``built test`` steps. 
It is easier and usually more efficient to have intermediate tasks on a build/dev process as it gives you more control on what tool to use for a particular task and how to configure it (eventually caching results, etc). In our particular case for example if you start hacking the unit test files only you don't need to waste time on typescript compilation or source bundling. 

On my machine:
``time (npm run build && npm test)``
> 10s
``time npm run test:unit
> 1s

You could argue that's what the ``npm run test:unit`` is for but I find it more convenient that way to build automation scripts like Lego bricks. A matter of preferences I guess.

However the README definitely lacks a "dev" or "contributing" section as you were not able to hack around just using the info in the repo and the common conventions...

**Comment by TehShrike** [comment]
Yeah, `git clone` + `npm it` is an extremely well-established convention for JS libraries.  I don't even look for a dev/contributing section in readmes before diving in.

**Comment by lorenzofox3** [comment]
> Yeah, `git clone` + `npm it` is an extremely well-established convention for JS libraries. I don't even look for a dev/contributing section in readmes before diving in.

I would say based on my experience that is less often the case as more and more Javascript projects have some built steps. 

But anyway the idea at the end is to improve the dev experience so, can we stick to my first comment ? Thanks

**Comment by TehShrike** [comment]
I'm only motivated to fix the test script, I'm ambivalent on adding other scripts

**Comment by lorenzofox3** [comment]
Ok, I'll do it ! thanks for your feedbak

**Pull request closed without merging**
